create OSError with arguments
socket.error is a deprecated alias of OSError since Python 3.3.

Passing no args and setting .errno attribute will make an empty message:

>>> e = socket.error()
>>> e.errno = 2
>>> raise e
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError

We need to create the exception like this:

>>> e = OSError(2, os.strerror(2))
>>> raise e
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory